### ISSUE TITLE
*.aurp format documentation

### ISSUE THREAD

**Issue by JKamsker** [Smertig/among-us-replay-mod#2]
Hey, 
im looking into creating ```aurp``` on my own. 
I wanted to ask wether there is any documentation available as my cpp skills are not the greatest.

Thanks!

**Comment by Smertig** [comment]
Hi! Thanks for your question.

I didn't publish any documentation for `aurp` format, because it's supposed to be internal binary format for interaction between `replay-mod` and `replayer`. I didn't expect anyone else to use it. Moreover I don't really want to keep documentation up-to-date.

Please, tell me more about your task. If it's one-time task, I'll publish short description of current format version. If you want to develop your own `aurp`-generator, I should think how to deal with it.

**Comment by JKamsker** [comment]
Well, i wanted to add an plugin to https://github.com/AeonLucid/Impostor which generates file with that format to be played afterwards.

**Comment by Smertig** [comment]
Sounds great!
I will publish some sort of documentation later.
