### ISSUE TITLE
General Question, feel free to close.

### ISSUE THREAD

**Issue by JacobAsmuth** [Smertig/among-us-replay-mod#8]
How did you generate the 'autogen' directory? I've been dissecting the game memory manually and it's a huge pain(Particularily with tasks). It seems like you have a tool that provided at least some of the work for you, which would be amazing for me to use as well.

**Comment by Smertig** [comment]
Honestly, the name `autogen` doesn't mean automatic code generation. It's just a directory with sources that I've obtained from game binary manually and/or partially automatically. Name `autogen` is used only by historical reasons.

On the question of automation, I use [Il2CppDumper](https://github.com/Perfare/Il2CppDumper) tool to extract functions (name, address, signature) and classes (name, layout, methods etc) from `GameAssembly.dll` + `Among Us_Data/il2cpp_data/Metadata/global-metadata.dat`.

Unfortunately, the developers have been using an obfuscator since **Among Us v2020.9.22s**, i.e. instead of `PlayerTask` class (`2020.6.9`) we have `FKAPFNAKPBG` (`2020.11.4`) or `PILBGHDHJLH` (`2020.12.9`). However, some structure members remain non-obfuscated so I use them as markers. Check out this repo for comments `// [marker]` ([example](https://github.com/Smertig/among-us-replay-mod/blob/master/source/autogen/PlayerTask.hpp#L18)).

P.S. [il2cpp.h](https://github.com/Smertig/among-us-replay-mod/files/5756873/il2cpp.h.txt), [dump.cs](https://github.com/Smertig/among-us-replay-mod/files/5756874/dump.cs.txt) - output of Il2CppDumper for non-obfuscated version `2020.6.9`, hope it helps.

**Comment by JacobAsmuth** [comment]
Awesome, thanks a bunch. Very helpful!
